
#pragma once 
enum
{
	ID_ITEM_CONFIGAPPDLG_TITLE=50,
	ID_ITEM_INSTRUMENTGROUP,
	ID_ITEM_SELFGROUP,
	ID_ITEM_VARIETYINFOSET,
	ID_ITEM_GROUPSET,
	//用户组设置，用于多账号
	ID_ITEM_USERGROUP,

	ID_ITEM_SHOW,
	ID_ITEM_FONTANDCOLOR,

	ID_ITEM_OPENORDER,
	ID_ITEM_GENERALSET,
	ID_ITEM_AUTOOPENCLOSESET,
	ID_ITEM_QUICKORDERSET,		//用于多账号
	ID_ITEM_KEYBOARDOPENODER,
	ID_ITEM_MOUSEOPENORDER,
	ID_ITEM_ADVANCEDSET,
	//下单策略，用于多账号
	ID_ITEM_ORDERSTRATEGY,
	ID_ITEM_BASEDMULTIPE,
	ID_ITEM_DISTRIBUTEBYSUM,
	ID_ITEM_ALIGNTOFISRTACCOUNT,
	ID_ITEM_ACCOUNTSCALEDIVEDED,
	ID_ITEM_CUSTOMVOLUMN,
    ID_ITEM_AutoDeriveOrderByFirstAccount,

	ID_ITEM_GENERALCANCELORDER,
	ID_ITEM_RISKMANAGER,
	ID_ITEM_PROMPT,
	ID_ITEM_TABLESET,
	ID_ITEM_QUOTETABLE,
	ID_ITEM_TRADERECORD,
	ID_ITEM_TRADESTATISTIC,
	ID_ITEM_POSITION,
	ID_ITEM_POSITIONDETAIL,
	ID_ITEM_INSTRUMENTLIST,
	ID_ITEM_ALLORDER,
	ID_ITEM_WAITTRADE,
	ID_ITEM_PARKEDORDER,
	ID_ITEM_ACCOUNT,
	ID_ITEM_QUERYORDERBATCH,
	ID_ITEM_QUERYORDERCONDITION,
	ID_ITEM_QUERYORDERPOSITION,
	ID_ITEM_ORDER_INSERT,
	ID_ITEM_COMBO_POSITION,
	ID_ITEM_ORDER_PLDETAIL,
	ID_ITEM_ORDER_POSIPL,
	ID_ITEM_MULTIACCOUNT,	//用于多账号
	ID_ITEM_MULTIPOSITION,//持仓汇总，用于多账号
};
#define wxLIST_CFG_VIEW (wxLCEXT_REPORT|wxLCEXT_VRULES|wxLCEXT_HRULES|wxLCEXT_SINGLE_SEL)
