ALTER TABLE "ACCOUNT"
   DROP CONSTRAINT FK_ACCOUNT_REFERENCE_IDCARD;

ALTER TABLE "ACCOUNT"
   DROP CONSTRAINT FK_ACCOUNT_REFERENCE_PERMISSI;

ALTER TABLE "BROKERINFO"
   DROP CONSTRAINT FK_BROKERIN_REFERENCE_ACCOUNT;

ALTER TABLE "MESSAGEINFO"
   DROP CONSTRAINT FK_MESSAGEI_REFERENCE_ACCOUNT;

ALTER TABLE "MESSAGETARGET"
   DROP CONSTRAINT FK_MESSAGET_REFERENCE_MESSAGEI;

ALTER TABLE "MESSAGEWAITFORSEND"
   DROP CONSTRAINT FK_MESSAGEW_REFERENCE_MESSAGEI;

ALTER TABLE "PERMISSION"
   DROP CONSTRAINT FK_PERMISSI_REFERENCE_ACCOUNT;

ALTER TABLE "SERVERADDR"
   DROP CONSTRAINT FK_SERVERAD_REFERENCE_SERVERGR;

ALTER TABLE "SERVERGROUP"
   DROP CONSTRAINT FK_SERVERGR_REFERENCE_BROKERIN;

ALTER TABLE "TRADEACCOUNT"
   DROP CONSTRAINT FK_TRADEACC_REFERENCE_ACCOUNT;

DROP INDEX "INDEX_TRADEACCOUNT";

DROP TABLE "ACCOUNT" CASCADE CONSTRAINTS;

DROP INDEX "INDEX_OWNERBROKERCODE";

DROP TABLE "BROKERINFO" CASCADE CONSTRAINTS;

DROP TABLE "IDCARD" CASCADE CONSTRAINTS;

DROP TABLE "MESSAGEINFO" CASCADE CONSTRAINTS;

DROP TABLE "MESSAGETARGET" CASCADE CONSTRAINTS;

DROP TABLE "MESSAGEWAITFORSEND" CASCADE CONSTRAINTS;

DROP INDEX "INDEX_OWNERNAMEMODULE";

DROP TABLE "PERMISSION" CASCADE CONSTRAINTS;

DROP TABLE "PERMISSIONMODULE" CASCADE CONSTRAINTS;

DROP TABLE "SERVERADDR" CASCADE CONSTRAINTS;

DROP INDEX "INDEX_SERVERGROUP";

DROP TABLE "SERVERGROUP" CASCADE CONSTRAINTS;

DROP INDEX "INDEX_OWNER_ACCT";

DROP TABLE "TRADEACCOUNT" CASCADE CONSTRAINTS;

DROP SEQUENCE "SEQ_ACCOUNTID";

DROP SEQUENCE "SEQ_ADDRID";

DROP SEQUENCE "SEQ_BROKERID";

DROP SEQUENCE "SEQ_IDCARDTYPE";

DROP SEQUENCE "SEQ_MODULEID";

DROP SEQUENCE "SEQ_MSGID";

DROP SEQUENCE "SEQ_PERMISSIONID";

DROP SEQUENCE "SEQ_SERVERNO";