#pragma once
//请在这个头文件中定义服务器端各模块函数接口的错误码
typedef int CF_ERROR;

#define  MAKE_ERROR_CODE(_base,_offset) \
	((int)( (int)(_base) << 16 ) + (int)(_offset))

#define CF_ERROR_SUCCESS 0               //成功
#define CF_ERROR_FAILURE -1              //失败(通用)

#define CF_ERROR_COMMON_BASE				 0x0000   //公用故障
#define CF_ERROR_NET_BASE					 0x0010   //网络故障
#define CF_ERROR_BUSSINESS_BASE				 0x0020   //业务错误
#define CF_ERROR_OPERATION_BASE				 0x0030   //用户操作性错误
#define CF_ERROR_DATABASE_BASE				 0x0040   //数据库错误
#define CF_ERROR_LOGIN_BASE					 0x0050   //登陆错误
#define CF_ERROR_INSTRUMENT_BASE			 0x0060   //合约错误
#define CF_ERROR_RATIO_BASE					 0x0070   //费率错误
#define CF_ERROR_SETTLEMENT_BASE			 0x0080   //结算错误
#define CF_ERROR_INPURORDER_BASE			 0x0090	  //交易执行错误
#define CF_ERROR_TRADERDATA_BASE			 0x00A0	  //交易数据管理
#define CF_ERROR_RISK_BASE					 0x00B0	  //风控
#define CF_ERROR_OFFER_BASE					 0x00C0	  //报盘
#define CF_ERROR_DATA_UPDATE_BASE			 0x00D0	  //基础数据更新
#define CF_ERROR_DATA_QUOT_BASE			     0x00E0	  //行情
#define CF_ERROR_DATA_STRATEGY_BASE			 0x00F0	  //策略
//公共错误
#define CF_ERROR_COMMON_INPUT_PARAM    MAKE_ERROR_CODE(CF_ERROR_COMMON_BASE,0x0001)  //输入错误
#define CF_ERROR_COMMON_MEMEORY	       MAKE_ERROR_CODE(CF_ERROR_COMMON_BASE,0x0002)  //内存错误
#define CF_ERROR_COMMON_NO_PRIVILEGE   MAKE_ERROR_CODE(CF_ERROR_COMMON_BASE,0x0003)  //权限不够

//网络故障
#define CF_ERROR_NET_CONNECT MAKE_ERROR_CODE(CF_ERROR_NET_BASE,0x0001)  //网络连接不上
#define CF_ERROR_NET_TIMEOUT MAKE_ERROR_CODE(CF_ERROR_NET_BASE,0x0002)  //网络连接超时
//登陆模块错误定义
#define CF_ERROR_LOGIN_PASS_INVALIDATE      MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x0001)   //登陆是否密码错误
#define CF_ERROR_LOGIN_SOCKET_NOT_EXIST     MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x0002)  //不存在该socket
#define CF_ERROR_LOGIN_USER_NOT_EXIST       MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x0003)  //不存在该用户
#define CF_ERROR_LOGIN_USER_NOT_USE         MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x0004)  //该用户没有启用
#define CF_ERROR_LOGIN_USER_PASSWORD_ERROR	MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x0005)	 //用户(交易员)修改密码时，原密码输入错误
#define CF_ERROR_LOGIN_USER_DATA_NOTREADY   MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x0006)	 //用户数据正在初始化，请稍后登录
#define CF_ERROR_LOGIN_TADRE_STATUS_INIT    MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x0007)	 //服务器正在初始化，请稍后登录
#define CF_ERROR_LOGIN_TADRE_STATUS_SETT    MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x0008)	 //服务器正在结算，请稍后登录
#define CF_ERROR_LOGIN_TADRE_STATUS_NOSETT  MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x0009)	 //没有日初结算单，请通知管理员进行结算，请稍后登录
#define CF_ERROR_LOGIN_TADRE_STATUS_END     MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x000a)	 //今日交易结束。
#define CF_ERROR_LOGIN_INVALIDE_USERID		MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x000b)	 //无效的用户ID
#define CF_ERROR_LOGIN_USER_UNPASSWORD_ERROR	MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x000c)	 //用户解锁密码时，密码输入错误
#define CF_ERROR_LOGIN_TADRE_STATUS_INITFAIL    MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x000d)	 //服务器初始化失败，无法登录
#define CF_ERROR_LOGIN_IP_INVALIDATE			MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x000e)   //不是从指定的IP地址过来的从服务器登录
#define CF_ERROR_LOGIN_USERTYPE_INVALIDATE      MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x000f)   //不是允许的用户类型
#define CF_ERROR_LOGIN_QUOTSERVER_ERROR         MAKE_ERROR_CODE(CF_ERROR_LOGIN_BASE,0x0010)   //用户未登录行情服务器 
//数据库错误定义
#define CF_ERROR_DATABASE_NOT_CONNECT		MAKE_ERROR_CODE(CF_ERROR_DATABASE_BASE,0x0001)	//数据库未连接
#define CF_ERROR_DATABASE_DUPLICATE_FIELD	MAKE_ERROR_CODE(CF_ERROR_DATABASE_BASE,0x0002)	//ORA-00001 字段重复，违反约束条件
#define CF_ERROR_DATABASE_RECODE_USED		MAKE_ERROR_CODE(CF_ERROR_DATABASE_BASE,0x0003)	//ORA-02292 数据正被其他表使用
#define CF_ERROR_DATABASE_NO_DEPENDENT		MAKE_ERROR_CODE(CF_ERROR_DATABASE_BASE,0x0004)	//ORA-02291 无法找到依赖项
#define CF_ERROR_DATABASE_OTHER_ERROR		MAKE_ERROR_CODE(CF_ERROR_DATABASE_BASE,0x0005)	//其他错误


//合约错误
#define CF_ERROR_NO_INSTRUMENTS MAKE_ERROR_CODE(CF_ERROR_INSTRUMENT_BASE,0x0001)  //没有合约


//费率错误
#define CF_ERROR_NO_COMMISSION  MAKE_ERROR_CODE(CF_ERROR_RATIO_BASE,0x0001)  //没有费率
#define CF_ERROR_NO_MARGIN      MAKE_ERROR_CODE(CF_ERROR_RATIO_BASE,0x0002)  //没有报证金率

//结算错误
#define CF_ERROR_NOT_SETTLEMENTTIME           MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0001)  //未到结算时间
#define CF_ERROR_NO_SETTLEMENTPRICE           MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0002)  //没有结算价
#define CF_ERROR_NO_TRADEDATA                 MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0003)  //没有成交记录
#define CF_ERROR_REDUPLICATE_TRADE            MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0004)  //数据库中已有此条成交记录
#define CF_ERROR_NO_POSITIONDETAIL            MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0005)  //没有持仓明细
#define CF_ERROR_NO_POSITION                  MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0006)  //没有持仓记录
#define CF_ERROR_NO_FUND                      MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0007)  //没有资金记录
#define CF_ERROR_REDUPLICATE_POSITIONDETAIL   MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0008)  //数据库中已有此条持仓明细
#define CF_ERROR_REDUPLICATE_POSITION         MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0009)  //数据库中已有此条持仓
#define CF_ERROR_TRADINGDAY_ERROR             MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0010)  //交易日错误，只能进行历史结算
#define CF_ERROR_NO_LASTSETTLEMENTPRICE       MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0011)  //没有上一交易日结算数据，无法进行今日结算
#define CF_ERROR_NO_SETTLEMENTINFO            MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0012)  //没有结算单
#define CF_ERROR_ADDTRADE_FAILD               MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0013)  //增加成交失败
#define CF_ERROR_MANULSETTLEMENT_FAILD        MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0014)  //服务器处于 结算状态
#define CF_ERROR_NOSERVICEGROUP_FAILD         MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0015)  //没有设置结算服务器组
#define CF_ERROR_TRADEDATASTATUSERROR_FAILD   MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0016)  //数据管理模块为非交易状态，自动结算失败
#define CF_ERROR_LOADHISTORYCOMMISSION_FAILD  MAKE_ERROR_CODE(CF_ERROR_SETTLEMENT_BASE,0x0017)  //无法加载此日期费率数据

//交易执行错误
#define CF_ERROR_USER_NOT_ENABLE				MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x0000)	//账户未启用
#define CF_ERROR_TRADE_FORBIDDEN				MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x0001)	//无交易权限
#define CF_ERROR_TRADE_LIMITED					MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x0002)	//该品种或合约被限制交易
#define CF_ERROR_TRADE_VERIFY_FAILD				MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x0003)	//审核未通过
#define CF_ERROR_TRADE_RISK_LIMITED				MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x0004)	//该合约或下单方向被风控方案限制下单
#define CF_ERROR_TRADE_STRATEGY_LIMITED			MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x0005)	//该合约或下单方向被交易策略限制下单
#define CF_ERROR_TRADE_ALREADY_CANCELED			MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x0006)	//已撤单
#define CF_ERROR_TRADE_USER_TRADE_NOTREADY		MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x0007)	//该用户的查询交易数据还没有准备好，请稍后再试
#define CF_ERROR_TRADE_HAS_VERIFYED				MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x0008)	//审核已审核
#define CF_ERROR_TRADE_VERIFYING				MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x0009)	//等待审核
#define CF_ERROR_TRADE_HAS_RECEVIED				MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x000a)    //报单已接收
#define CF_ERROR_TRADE_HAS_SENDCTP              MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x000b)    //报单已转发到CTP
#define CF_ERROR_TRADE_HAS_RISK_RECEVIED        MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x000c)    //强平单已接收
#define CF_ERROR_TRADE_FORCE_ORDED_NO_ACTION    MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x000d)    //强平单不能撤单
#define CF_ERROR_RISK_ALL_INSTRUMENT_ORDER	    MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x000e)    //风控限制 所有合约限制下单
#define CF_ERROR_RISK_SINGLE_INSTRUMENT_ORDER	MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x000f)    //风控限制 单合约限制下单
#define CF_ERROR_RISK_ALL_INSTRUMENT_OPEN	    MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x0010)    //风控限制 所有合约限制开仓
#define CF_ERROR_RISK_SINGLE_INSTRUMENT_OPEN	MAKE_ERROR_CODE(CF_ERROR_INPURORDER_BASE,0x0011)    //风控限制 单合约限制开仓
//交易数据管理错误
#define CF_ERROR_TRADEDATA_NO_USER_DATA   		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0000)	//没有该用户的数据
#define CF_ERROR_TRADEDATA_NO_INSTRUMENTS 		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0001)	//返回数据没有准备好，请稍后再次查询
#define CF_ERROR_TRADEDATA_NO_COMMISSION 		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0002)	//返回数据没有准备好，请稍后再次查询
#define CF_ERROR_TRADEDATA_NO_MARGIN     		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0003)	//返回数据没有准备好，请稍后再次查询
#define CF_ERROR_TRADEDATA_NO_FUND      		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0004)	//返回数据没有准备好，请稍后再次查询
#define CF_ERROR_TRADEDATA_NO_POSITION     		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0005)	//返回数据没有准备好，请稍后再次查询
#define CF_ERROR_TRADEDATA_NO_POSDETAIL   		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0006)	//返回数据没有准备好，请稍后再次查询
#define CF_ERROR_TRADEDATA_NO_COMPOS      		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0007)	//返回数据没有准备好，请稍后再次查询
#define CF_ERROR_TRADEDATA_NO_COMPOSDETAIL		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0008)	//返回数据没有准备好，请稍后再次查询
#define CF_ERROR_TRADEDATA_NO_ORDER      		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0009)	//返回数据没有准备好，请稍后再次查询
#define CF_ERROR_TRADEDATA_NO_TRADE     		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x000A)	//返回数据没有准备好，请稍后再次查询
#define CF_ERROR_NOINITED                		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x000b)	//状态没有初始化，无法完成指定的动作
#define CF_ERROR_TRADEDATA_FUNDINOUT_DENY		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x000c)	//状态没有初始化，无法完成指定的动作	
#define CF_ERROR_TRADEDATA_SETTMENT_NOINIT		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x000d)	//日初数据没有准备好，只能做历史结算	
#define CF_ERROR_TRADEDATA_SETTMENT_NOTRAING	MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x000e)	//盘中数据错误，只能做历史结算
#define CF_ERROR_TRADEDATA_TRADE_FROM_OTHER		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x000f)	//是从别的客户端产生的成交
#define CF_ERROR_TRADEDATA_NOSETTLEMENT_PRICE	MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0010)	//结算价不全
#define CF_ERROR_TRADEDATA_NOTRADINGDAY			MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0011)	//没有交易日，不能进行盘中结算
#define CF_ERROR_TRADEDATA_TODAYHAD				MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0012)	//今天已结算过了，只能进行历史结算
#define CF_ERROR_TRADEDATA_EXCHANGE_ISTRADE     MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0013)	//正在交易，不能进行结算动作
#define CF_ERROR_TRADEDATA_INITING			    MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0014)    //数据正在初始化阶段，不能进行该操作
#define CF_ERROR_TRADEDATA_INIT_NORELEATION	    MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0015)    //该用户没有关联交易员，无法初始化
#define CF_ERROR_TRADEDATA_INIT_ACCOUNT_NOLOGIN MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0016)    //该用户管理的委托交易账号没有登陆，请先登陆该委托交易账号
#define CF_ERROR_TRADEDATA_INIT_ACCOUNT_NOCOMM  MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0017)    //该用户管理的委托交易账号没有查询到费率，可能账号登陆有异常
#define CF_ERROR_TRADEDATA_NOTTRADINGDAY		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0018)    //非交易日，不能进行历史结算
#define CF_ERROR_TRADEDATA_NOTMATCH_STATUS		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0019)    //服务器正处于交易中或结算中，不支持该操作
#define CF_ERROR_TRADEDATA_HAS_POSITION			MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0020)    //该用户还有持仓，不能删除。
#define CF_ERROR_TRADEDATA_HAS_INITED			MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0021)    //已初始化成功，不用再初始化
#define CF_ERROR_TRADEDATA_FORBID_REINIT		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0022)    //当前服务器状态不符合重启设定
#define CF_ERROR_TRADEDATA_NOT_ENOUGH_FUND      MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0023)	//资金不足
#define CF_ERROR_TRADEDATA_ACCOUNT_ISLOGIN      MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0024)	//当前委托交易帐号是登陆状态，不能删除
#define CF_ERROR_TRADEDATA_FUNDIN_DENY_NOINIT	MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0025)	//用户未初始化，不能进行出入金操作
#define CF_ERROR_TRADEDATA_USER_LOGIN			MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0026)	//用户已登陆
#define CF_ERROR_TRADEDATA_FORBID_USERINIT      MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0027)	//当前服务器状态不能初始化用户，请重新初始化服务器后再次尝试
#define CF_ERROR_TRADEDATA_FORBID_ACCOUNTLOING  MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0028)	//当前服务器状态不能登陆委托交易帐号，请重新初始化服务器后再次尝试
#define CF_ERROR_TRADEDATA_FORBID_QRYUSER		MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x0029)	//当前服务器状态不是交易状态，查询不到用户初始化状态
#define CF_ERROR_TRADEDATA_FORBID_QRYACCOUNT    MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x002a)	//当前服务器状态不是交易状态，查询不到委托交易帐号登陆状态
#define CF_ERROR_TRADEDATA_WRONG_INSTRUMENT     MAKE_ERROR_CODE(CF_ERROR_TRADERDATA_BASE,0x002b)	//合约代码有误

//终端用户操作错误定义
#define CF_ERROR_OPERATION_DEL_TRADEACCOUNT      MAKE_ERROR_CODE(CF_ERROR_OPERATION_BASE,0x0001)   //删除委托交易账号错误
#define CF_ERROR_OPERATION_DEL_FINANCEPRODUCT    MAKE_ERROR_CODE(CF_ERROR_OPERATION_BASE,0x0002)   //删除理财产品错误
#define CF_ERROR_OPERATION_DEL_TRADESTRATEGY     MAKE_ERROR_CODE(CF_ERROR_OPERATION_BASE,0x0003)   //删除交易策略错误
#define CF_ERROR_OPERATION_DEL_ORGANIZATION_HAVE_TRDER      MAKE_ERROR_CODE(CF_ERROR_OPERATION_BASE,0x0004)   //删除组织机构错误1
#define CF_ERROR_OPERATION_DEL_ORGANIZATION_NO_LEAFNODE     MAKE_ERROR_CODE(CF_ERROR_OPERATION_BASE,0x0005)   //删除组织机构错误2
#define CF_ERROR_OPERATION_DEL_ROLE             MAKE_ERROR_CODE(CF_ERROR_OPERATION_BASE,0x0006)    //删除角色错误
#define CF_ERROR_TRADEDATA_NO_QUTO				MAKE_ERROR_CODE(CF_ERROR_OPERATION_BASE,0x000f)   //没有行情
#define CF_ERROR_TRADEDATA_NOT_ENOUGH_VOLOMN	MAKE_ERROR_CODE(CF_ERROR_OPERATION_BASE,0x0010)   //没有足够的可平量
#define CF_ERROR_OPERATION_DEL_BROKER	        MAKE_ERROR_CODE(CF_ERROR_OPERATION_BASE,0x0011)   //有委托交易账号与此关联，无法删除

//风控服务端返回错误信息
#define CF_ERROR_RISK_SETLIMITTRADE							MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x0001)   //设置限制交易失败
#define CF_ERROR_RISK_SETMEMUALVERIFY						MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x0002)   //设置手动审核失败
#define CF_ERROR_RISK_VERIFYORDERFAIL						MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x0003)   //未成交单审核失败
#define CF_ERROR_RISK_SETMEMUALVERIFY_NOPRIVILEDGE			MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x0004)   //没有设置手动审核权限
#define CF_ERROR_RISK_LIMITTRADE_NOPRIVILEDGE				MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x0005)   //没有限制交易权限
#define CF_ERROR_RISK_FORCECLOSE_NOPRIVILEDGE				MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x0006)   //没有强平权限
#define CF_ERROR_RISK_ADDPLAN_NOPRIVILEDGE					MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x0007)   //没有增加删除风控方案权限
#define CF_ERROR_RISK_DELETEPLAN_NOPRIVILEDGE				MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x0008)   //没有删除风控方案权限
#define CF_ERROR_RISK_USEPLAN_NOPRIVILEDGE					MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x0009)   //没有启用开关风控方案权限
#define CF_ERROR_HISTORY_RISK_EVENT_QUERY_NOPRIVILEDGE		MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x000a)   //没有历史风险事件查询权限
#define CF_ERROR_HISTROY_MSG_RECORD_QUERY_NOPRIVILEDGE		MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x000b)   //没有历史消息记录查询权限
#define CF_ERROR_HISTROY_FUND_SUTTLE_QUERY_NOPRIVILEDGE		MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x000c)   //没有历史基金净值查询权限
#define CF_ERROR_ORDER_VERIFY_RECORD_QUERY_NOPRIVILEDGE		MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x000d)   //没有报单审核记录查询权限
#define CF_ERROR_FORCE_CLOSE_RECORD_QUERY_NOPRIVILEDGE		MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x000e)   //没有强平记录查询权限
#define CF_ERROR_QUERY_HISTORY_FUND_NOPRIVILEDGE			MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x000f)   //没有查询历史资金权限
#define CF_ERROR_QUERY_HISTORY_POSITION_NOPRIVILEDGE		MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x0010)   //没有查询历史持仓权限
#define CF_ERROR_QUERY_HISTORY_POSITION_DETAIL_NOPRIVILEDGE	MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x0011)   //没有查询历史持仓明细权限
#define CF_ERROR_QUERY_HISTORY_TRADE_NOPRIVILEDGE			MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x0012)   //没有查询历史成交权限
#define CF_ERROR_QUERY_HISTORY_ORDER_NOPRIVILEDGE			MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x0013)   //没有查询历史报单权限
#define CF_ERROR_CONTROL_SERVER_QUOT_RESET_NOPRIVILEDGE		MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x0014)   //没有行情服务器重启权限
#define CF_ERROR_CONTROL_TIME_QUOT_SETUP_NOPRIVILEDGE		MAKE_ERROR_CODE(CF_ERROR_RISK_BASE,0x0015)   //没有行情服务器定时重启时间设置权限
//报盘
#define CF_ERROR_RISK_NETWORKCONNECTFAIL		MAKE_ERROR_CODE(CF_ERROR_OFFER_BASE,0x0001)   //网络连接失败
#define CF_ERROR_RISK_NOTPROCESSFULL     		MAKE_ERROR_CODE(CF_ERROR_OFFER_BASE,0x0002)   //表示未处理请求超过许可数
#define CF_ERROR_RISK_NOTPROCESSFULLEACHSECOND  MAKE_ERROR_CODE(CF_ERROR_OFFER_BASE,0x0003)   //表示每秒发送请求数超过许可数
#define CF_ERROR_RISK_NOTVALIDORDER 			MAKE_ERROR_CODE(CF_ERROR_OFFER_BASE,0x0004)   //不是有效的下单
#define CF_ERROR_RISK_NOTVALIDACTION			MAKE_ERROR_CODE(CF_ERROR_OFFER_BASE,0x0005)   //无法有效的撤单，找不到已有的报单号
#define CF_ERROR_RISK_ACCOUNTCONNECTFAIL		MAKE_ERROR_CODE(CF_ERROR_OFFER_BASE,0x0006)   //账号与ctp连接断开
//基础数据更新后的提示
#define CF_ERROR_DATA_UPDATE_ORG            MAKE_ERROR_CODE(CF_ERROR_DATA_UPDATE_BASE,0x0001)   //组织机构基础数据更新，请重新登录
#define CF_ERROR_DATA_UPDATE_PRODUCT        MAKE_ERROR_CODE(CF_ERROR_DATA_UPDATE_BASE,0x0002)   //理财产品基础数据更新，请重新登录
#define CF_ERROR_DATA_UPDATE_BROKER  	    MAKE_ERROR_CODE(CF_ERROR_DATA_UPDATE_BASE,0x0003)   //经纪公司基础数据更新，请重新登录
#define CF_ERROR_DATA_UPDATE_SERVERGROUP    MAKE_ERROR_CODE(CF_ERROR_DATA_UPDATE_BASE,0x0004)   //服务器组基础数据更新，请重新登录
#define CF_ERROR_DATA_UPDATE_SERVERADDR     MAKE_ERROR_CODE(CF_ERROR_DATA_UPDATE_BASE,0x0005)   //服务器组地址基础数据更新，请重新登录
#define CF_ERROR_DATA_UPDATE_ACCOUNT        MAKE_ERROR_CODE(CF_ERROR_DATA_UPDATE_BASE,0x0006)   //委托交易账户基础数据更新，请重新登录
#define CF_ERROR_DATA_UPDATE_STRATEGY  	    MAKE_ERROR_CODE(CF_ERROR_DATA_UPDATE_BASE,0x0007)   //交易策略基础数据更新，请重新登录
#define CF_ERROR_DATA_UPDATE_USER           MAKE_ERROR_CODE(CF_ERROR_DATA_UPDATE_BASE,0x0008)   //系统用户基础数据更新，请重新登录
#define CF_ERROR_DATA_UPDATE_ROLE           MAKE_ERROR_CODE(CF_ERROR_DATA_UPDATE_BASE,0x0009)   //角色基础数据更新，请重新登录

#define CF_ERROR_DATA_UPDATE_ROLEANDPRIVILEGE   MAKE_ERROR_CODE(CF_ERROR_DATA_UPDATE_BASE,0x0010)   //角色和权限关系更新，请重新登录
#define CF_ERROR_DATA_UPDATE_USERANDROLE        MAKE_ERROR_CODE(CF_ERROR_DATA_UPDATE_BASE,0x0011)   //用户和角色关系更新，请重新登录
#define CF_ERROR_DATA_UPDATE_USERANDORG         MAKE_ERROR_CODE(CF_ERROR_DATA_UPDATE_BASE,0x0012)   //用户和组织机构关系更新，请重新登录
#define CF_ERROR_DATA_UPDATE_USERANDPRODUCT     MAKE_ERROR_CODE(CF_ERROR_DATA_UPDATE_BASE,0x0013)   //用户和理财产品关系更新，请重新登录
#define CF_ERROR_DATA_UPDATE_STRATEGYANDORG     MAKE_ERROR_CODE(CF_ERROR_DATA_UPDATE_BASE,0x0014)   //交易策略和组织机构更新，请重新登录
//行情
#define CF_ERROR_DATA_QUOT_SUBSCRIBE        MAKE_ERROR_CODE(CF_ERROR_DATA_QUOT_BASE,0x0001)   //订阅行情失败
#define CF_ERROR_DATA_QUOT_UNSUBSCRIBE      MAKE_ERROR_CODE(CF_ERROR_DATA_QUOT_BASE,0x0002)   //退订行情失败

//策略
#define CF_ERROR_DATA_STRATEGY_EXISTANDUSE				MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0001)   //[%s]策略已经存在，而且处于启用状态
#define CF_ERROR_DATA_STRATEGY_SAVEDLLFAIL				MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0002)   //存储策略dll失败
#define CF_ERROR_DATA_STRATEGY_SAVEZIPFAIL				MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0003)   //存储策略ZIP失败
#define CF_ERROR_DATA_STRATEGY_NOTBELONGTOUPLOADER      MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0004)   //存储策略不属于该交易员
#define CF_ERROR_DATA_STRATEGY_NOTEXIST					MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0005)   //策略不存在
#define CF_ERROR_DATA_STRATEGY_NOTBELONGTOUPLOADER_PRIVATE				MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0006)   //该策略不是属于该交易员，而且该策略为私有
#define CF_ERROR_DATA_READDLLFAIL						MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0007)   //读取该策略dll文件失败
#define CF_ERROR_DATA_READZIPFAIL						MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0008)   //读取该策略源代码文件失败
#define CF_ERROR_DATA_IndexIsUsing						MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0009)   //[%s]指标所对应的[%s]策略有处于运行当中
#define CF_ERROR_DATA_INDEX_NOTEXIST					MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0010)   //指标不存在
#define CF_ERROR_DATA_INDEX_NOTBELONGTOUPLOADER_PRIVATE				MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0011)   //该指标不是属于该交易员，而且该策略为私有
#define CF_ERROR_DATA_INDEX_SAVEDLLFAIL				MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0012)   //存储指标dll失败
#define CF_ERROR_DATA_STRATEGY_NOTBELONGTOUPLOADER_USE				MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0013)   //该策略不是属于该交易员，而且该策略为运行状态
#define CF_ERROR_DATA_INSTANCE_NOTBELONGTOUPLOADER				MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0014)   //该策略方案不是属于该交易员
#define CF_ERROR_DATA_INSTANCE_NOTEXIST					MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0015)   //策略方案不存在
#define CF_ERROR_DATA_STRATEGY_NOUSERNAME				MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0016)   //没有上传人，不允许上传
#define CF_ERROR_DATA_STRATEGY_NOTBELONGTOUPLOADER_PUBLIC				MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0017)   //策略或指标源程序属于其他交易员不能下载
#define CF_ERROR_DATA_UPLOAD_BACKFAIL				MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0027)   //上传之前备份原有指标或者策略失败
#define CF_ERROR_DATA_UPLOAD_RollBACKFAIL				MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0028)   //备份的原有指标或者策略还原失败
#define CF_ERROR_DATA_UPLOAD_FAIL 				    MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0029)   //本次上传失败，系统已经恢复原来的策略或者指标
#define CF_ERROR_GET_COMMISSION_FAIL 				    MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0032)   //查询费率[%s]失败
#define CF_ERROR_GET_MARGINATE_FAIL 				    MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0033)   //查询保证金率[%s]失败
#define CF_ERROR_NO_ACCOUNT_FAIL 				    MAKE_ERROR_CODE(CF_ERROR_DATA_STRATEGY_BASE,0x0034)   //查询失败,改子账号对应的主账号不存在

///////////////////////////////////////////////////////////////////////////////
//格式化错误代码为错误字符串FormatErrorCode
//Input: nErrorCode 为具体的错误码
//Output: 如果有则返回具体的错误字符串
//        如果没有找到对应的错误码，则返回空串
/////////////////////////////////////////////////////////////////////////////////
inline const char * FormatErrorCode(const int nErrorCode)
{
	switch(nErrorCode)
	{
	case CF_ERROR_COMMON_MEMEORY:               return "内存错误";
	case CF_ERROR_COMMON_INPUT_PARAM:           return "输入参数错误";
	case CF_ERROR_COMMON_NO_PRIVILEGE:          return "该用户没有权限执行该动作";
	case CF_ERROR_LOGIN_PASS_INVALIDATE:		return "用户名或密码错误";
    case CF_ERROR_LOGIN_USER_NOT_USE:		    return "用户状态没有启用，无法登陆";
	case CF_ERROR_LOGIN_SOCKET_NOT_EXIST:       return "该连接已失效，无法注销";
	case CF_ERROR_LOGIN_USER_DATA_NOTREADY:     return "用户数据正在初始化，请稍后尝试";
	case CF_ERROR_LOGIN_TADRE_STATUS_INIT:      return "服务器正在初始化，请稍后登录";
	case CF_ERROR_LOGIN_TADRE_STATUS_SETT:      return "服务器正在结算，请稍后登录";
	case CF_ERROR_LOGIN_TADRE_STATUS_NOSETT:    return "没有日初结算单，请通知管理员进行结算，请稍后登录";
	case CF_ERROR_LOGIN_TADRE_STATUS_END:       return "今日交易结束，无法登录";
	case CF_ERROR_LOGIN_INVALIDE_USERID:		return "无效的用户ID，无法登录";
	case CF_ERROR_LOGIN_USER_NOT_EXIST:         return "不存在该用户，无法登录";
	case CF_ERROR_LOGIN_TADRE_STATUS_INITFAIL:  return "服务器初始化失败，无法登录";
	case CF_ERROR_LOGIN_IP_INVALIDATE:			return "不是从指定的IP地址过来的从服务器登录";
	case CF_ERROR_LOGIN_USERTYPE_INVALIDATE:	return "该客户端不能登陆到该服务器";
	case CF_ERROR_LOGIN_QUOTSERVER_ERROR:	    return "用户未登录行情服务器";

	case CF_ERROR_NO_INSTRUMENTS:				return "没有可以返回的合约";	
	case CF_ERROR_NOT_SETTLEMENTTIME:		    return "未到结算时间";
	case CF_ERROR_NO_SETTLEMENTPRICE:		    return "没有结算价";
	case CF_ERROR_DATABASE_NOT_CONNECT:		    return "数据库位连接";
	case CF_ERROR_DATABASE_DUPLICATE_FIELD:		return "字段重复，违反唯一性约束条件";
	case CF_ERROR_DATABASE_NO_DEPENDENT:		return "无法找到依赖项";
	case CF_ERROR_DATABASE_RECODE_USED:			return "记录正在被使用";
	case CF_ERROR_DATABASE_OTHER_ERROR:			return "数据库操作错误";
	case CF_ERROR_REDUPLICATE_TRADE:		    return "数据库中已有此条成交记录";
	case CF_ERROR_NO_COMMISSION:		        return "没有费率记录";
	case CF_ERROR_NO_TRADEDATA:		            return "没有成交记录";
	case CF_ERROR_NO_FUND:		                return "没有资金记录";
	case CF_ERROR_NO_POSITIONDETAIL:		    return "没有持仓明细";
	case CF_ERROR_NO_POSITION:		            return "没有持仓记录";
	case CF_ERROR_REDUPLICATE_POSITIONDETAIL:	return "数据库中已有此条持仓明细";
	case CF_ERROR_REDUPLICATE_POSITION:	        return "数据库中已有此条持仓";
	case CF_ERROR_NO_LASTSETTLEMENTPRICE:	    return "没有上一交易日结算数据，无法进行今日结算";
	case CF_ERROR_NO_SETTLEMENTINFO:	        return "没有结算单";
	case CF_ERROR_ADDTRADE_FAILD:	            return "新增、修改成交失败，可平量不足";
	case CF_ERROR_MANULSETTLEMENT_FAILD:	    return "服务器已处于结算状态";
	case CF_ERROR_NOSERVICEGROUP_FAILD:	        return "没有设置结算服务器组";
	case CF_ERROR_TRADEDATASTATUSERROR_FAILD:	return "数据管理模块为非交易状态，自动结算失败";
	case CF_ERROR_LOADHISTORYCOMMISSION_FAILD:	return "无法加载此日期费率数据";

	
	case CF_ERROR_TRADEDATA_NO_USER_DATA:       return "服务器端没有该用户的数据，请联系管理员";
	case CF_ERROR_TRADEDATA_NO_INSTRUMENTS:     return "合约数据没有准备好，请稍后再次查询";
	case CF_ERROR_TRADEDATA_NO_COMMISSION:      return "手续费率数据没有准备好，请稍后再次查询";
	case CF_ERROR_TRADEDATA_NO_MARGIN:          return "保证金率数据没有准备好，请稍后再次查询";
	case CF_ERROR_TRADEDATA_NO_FUND:            return "资金数据没有准备好，请稍后再次查询";
	case CF_ERROR_TRADEDATA_NO_POSITION:        return "持仓数据没有准备好，请稍后再次查询";
	case CF_ERROR_TRADEDATA_NO_POSDETAIL:       return "持仓明细数据没有准备好，请稍后再次查询";
	case CF_ERROR_TRADEDATA_NO_COMPOS:          return "组合持仓数据没有准备好，请稍后再次查询";
	case CF_ERROR_TRADEDATA_NO_COMPOSDETAIL:    return "组合持仓明细没有准备好，请稍后再次查询";
	case CF_ERROR_TRADEDATA_NO_ORDER :          return "报单数据没有准备好，请稍后再次查询";
	case CF_ERROR_TRADEDATA_NO_TRADE:           return "成交数据没有准备好，请稍后再次查询";
	case CF_ERROR_TRADEDATA_FUNDINOUT_DENY :    return "出入金只能在盘中进行";
	case CF_ERROR_NOINITED:                     return "状态没有初始化，无法完成指定的动作";
	case CF_ERROR_TRADEDATA_SETTMENT_NOINIT:    return "服务器正在初始化状态，不能进行结算，请稍候再试";
	case CF_ERROR_TRADEDATA_SETTMENT_NOTRAING:	return "盘中数据错误，只能做历史结算";
	case CF_ERROR_TRADEDATA_NO_QUTO:			return "没有行情";
	case CF_ERROR_TRADEDATA_NOTRADINGDAY:		return "没有交易日，不能进行结算";
	case CF_ERROR_TRADEDATA_TODAYHAD:			return "今天已结算过了，只能进行历史结算";
	case CF_ERROR_TRADEDATA_NOT_ENOUGH_VOLOMN:	return "没有足够的可平量";
	case CF_ERROR_TRADEDATA_NOSETTLEMENT_PRICE: return "结算价不全";
	case CF_ERROR_TRADINGDAY_ERROR:             return "交易日错误，只能进行历史结算";
	case CF_ERROR_TRADEDATA_EXCHANGE_ISTRADE :  return "正在交易状态，不能进行结算";
	case CF_ERROR_TRADEDATA_INITING:            return "数据正在初始化，不能进行该操作";
	case CF_ERROR_TRADEDATA_INIT_NORELEATION:   return "该用户没有关联委托交易帐号，无法初始化";
	case CF_ERROR_TRADEDATA_INIT_ACCOUNT_NOLOGIN: return "该用户管理的委托交易账号没有登陆，请先登陆该委托交易账号";
	case CF_ERROR_TRADEDATA_INIT_ACCOUNT_NOCOMM:  return "该用户管理的委托交易账号没有查询到费率，可能账号登陆有异常";
	case CF_ERROR_TRADEDATA_NOTTRADINGDAY:      return "非交易日，不能进行结算";
	case CF_ERROR_TRADEDATA_NOTMATCH_STATUS:    return "该操作在只能在服务器处于结算完成状态,无交易日状态下才能操作";
	case CF_ERROR_TRADEDATA_HAS_POSITION:		return "该用户还有持仓，不能修改委托交易帐号";
	case CF_ERROR_TRADEDATA_HAS_INITED:			return "已初始化成功，不用再初始化";
	case CF_ERROR_TRADEDATA_FORBID_REINIT:      return "当前服务器状态不符合重启设定";
	case CF_ERROR_TRADEDATA_NOT_ENOUGH_FUND:    return "资金不足";
	case CF_ERROR_TRADEDATA_ACCOUNT_ISLOGIN:    return "当前委托交易帐号是登陆状态，不能删除";
	case CF_ERROR_TRADEDATA_FUNDIN_DENY_NOINIT: return "用户未初始化，不能进行出入金操作";
	case CF_ERROR_TRADEDATA_USER_LOGIN:			return "有关联的用户处于登录状态，无法删除";

    case CF_ERROR_OPERATION_DEL_TRADEACCOUNT:   return "有交易员正在使用此委托交易账号，无法删除";
    case CF_ERROR_OPERATION_DEL_FINANCEPRODUCT: return "有交易员正在使用此理财产品，无法删除";
    case CF_ERROR_OPERATION_DEL_TRADESTRATEGY:  return "有资管组织存在交易策略，无法删除";
    case CF_ERROR_OPERATION_DEL_ORGANIZATION_HAVE_TRDER:   return "有用户在此资管组织下，无法删除";
    case CF_ERROR_OPERATION_DEL_ORGANIZATION_NO_LEAFNODE:   return "此资管组织包含其他组织，无法删除";
    case CF_ERROR_OPERATION_DEL_ROLE:           return "有管理员或风控员正在使用此角色，无法删除";
    case CF_ERROR_OPERATION_DEL_BROKER:         return "有委托交易账号与此关联，无法删除";


	case CF_ERROR_USER_NOT_ENABLE:				return "账户未启用";
	case CF_ERROR_TRADE_FORBIDDEN:				return "无交易权限";
	case  CF_ERROR_TRADE_LIMITED:				return "该品种或合约被限制交易";
	case CF_ERROR_TRADE_VERIFY_FAILD:			return "审核未通过";
	case CF_ERROR_TRADE_RISK_LIMITED:			return "该合约或下单方向被风控方案限制下单";
	case CF_ERROR_TRADE_STRATEGY_LIMITED:		return "该合约或下单方向被交易策略限制下单";
	case CF_ERROR_TRADE_ALREADY_CANCELED:		return "已撤单";
	case CF_ERROR_TRADE_USER_TRADE_NOTREADY:	return "该用户的查询交易数据还没有准备好，请稍后再试";
	case CF_ERROR_TRADE_HAS_VERIFYED:           return "报单已审核";
	case CF_ERROR_TRADE_VERIFYING:				return "正在审核中";
	case CF_ERROR_TRADE_HAS_RECEVIED:			return "报单已接收";
	case CF_ERROR_TRADE_HAS_SENDCTP:			return "报单已转发到CTP";
	case CF_ERROR_TRADE_HAS_RISK_RECEVIED:		return "强平单已接收";
	case CF_ERROR_TRADE_FORCE_ORDED_NO_ACTION:  return "强平单不能撤单";
	case CF_ERROR_RISK_ALL_INSTRUMENT_ORDER:	return "风控限制 所有合约限制下单";
	case CF_ERROR_RISK_SINGLE_INSTRUMENT_ORDER:	return "风控限制 单合约限制下单";
	case CF_ERROR_RISK_ALL_INSTRUMENT_OPEN:	    return "风控限制 所有合约限制开仓";
	case CF_ERROR_RISK_SINGLE_INSTRUMENT_OPEN:	return "风控限制 单合约限制开仓";

	case CF_ERROR_TRADEDATA_FORBID_USERINIT:	return "当前服务器状态不能初始化用户，请重新初始化服务器后再次尝试";
	case CF_ERROR_TRADEDATA_FORBID_ACCOUNTLOING:return "当前服务器状态不能登陆委托交易帐号，请重新初始化服务器后再次尝试";
	case CF_ERROR_TRADEDATA_FORBID_QRYUSER:		return "当前服务器状态不是交易状态，查询不到用户初始化状态";
	case CF_ERROR_TRADEDATA_FORBID_QRYACCOUNT:  return "当前服务器状态不是交易状态，查询不到委托交易帐号登陆状态";
	case CF_ERROR_TRADEDATA_WRONG_INSTRUMENT:   return "合约代码有误";
	case CF_ERROR_RISK_SETLIMITTRADE:           return "设置限制交易失败";
	case CF_ERROR_RISK_SETMEMUALVERIFY:			return "设置手动审核失败";
	case CF_ERROR_RISK_VERIFYORDERFAIL:         return "未成交单审核失败";
	case CF_ERROR_RISK_SETMEMUALVERIFY_NOPRIVILEDGE: return "没有手动审核权限";
	case CF_ERROR_RISK_LIMITTRADE_NOPRIVILEDGE:		 return "没有限制交易权限";
	case CF_ERROR_RISK_FORCECLOSE_NOPRIVILEDGE:		 return "没有强平权限";
	case CF_ERROR_RISK_ADDPLAN_NOPRIVILEDGE:		 return "没有增加修改风控方案的权限";
	case CF_ERROR_RISK_DELETEPLAN_NOPRIVILEDGE:		 return "没有删除风控方案的权限";
	case CF_ERROR_RISK_USEPLAN_NOPRIVILEDGE:		 return "没有启用停用风控方案的权限";
	case CF_ERROR_HISTORY_RISK_EVENT_QUERY_NOPRIVILEDGE:		 return "没有历史风险事件查询权限";
	case CF_ERROR_HISTROY_MSG_RECORD_QUERY_NOPRIVILEDGE:		 return "没有历史消息记录查询权限";
	case CF_ERROR_HISTROY_FUND_SUTTLE_QUERY_NOPRIVILEDGE:		 return "没有历史基金净值查询权限";
	case CF_ERROR_ORDER_VERIFY_RECORD_QUERY_NOPRIVILEDGE:		 return "没有报单审核记录查询权限";
	case CF_ERROR_FORCE_CLOSE_RECORD_QUERY_NOPRIVILEDGE:		 return "没有强平记录查询权限";
	case CF_ERROR_QUERY_HISTORY_FUND_NOPRIVILEDGE:				 return "没有查询历史资金权限";
	case CF_ERROR_QUERY_HISTORY_POSITION_NOPRIVILEDGE:			 return "没有查询历史持仓权限";
	case CF_ERROR_QUERY_HISTORY_POSITION_DETAIL_NOPRIVILEDGE:	 return "没有查询历史持仓明细权限";
	case CF_ERROR_QUERY_HISTORY_TRADE_NOPRIVILEDGE:				 return "没有查询历史成交权限";
	case CF_ERROR_QUERY_HISTORY_ORDER_NOPRIVILEDGE:			     return "没有查询历史报单权限";
	case CF_ERROR_CONTROL_SERVER_QUOT_RESET_NOPRIVILEDGE:		 return "没有行情服务器重启权限";
	case CF_ERROR_CONTROL_TIME_QUOT_SETUP_NOPRIVILEDGE:		     return "没有行情服务器定时重启时间设置权限";

	case CF_ERROR_RISK_NETWORKCONNECTFAIL:				return "网络连接失败";
	case CF_ERROR_RISK_NOTPROCESSFULL:					return "表示未处理请求超过许可数";
	case CF_ERROR_RISK_NOTPROCESSFULLEACHSECOND:		return "表示每秒发送请求数超过许可数";
	case CF_ERROR_RISK_NOTVALIDORDER:					return "不是有效的下单";
	case CF_ERROR_RISK_NOTVALIDACTION:					return "无法有效的撤单，找不到已有的报单号";
	case CF_ERROR_RISK_ACCOUNTCONNECTFAIL:				return "账号与ctp连接断开";

    case CF_ERROR_LOGIN_USER_PASSWORD_ERROR:    return "用户修改密码时，原密码输入错误";
    case CF_ERROR_LOGIN_USER_UNPASSWORD_ERROR:  return "用户解锁密码时，密码输入错误";

    case CF_ERROR_DATA_UPDATE_ORG:            return "组织机构基础数据更新，请重新登录!";
    case CF_ERROR_DATA_UPDATE_PRODUCT:        return "理财产品基础数据更新，请重新登录!";
    case CF_ERROR_DATA_UPDATE_BROKER:  	      return "经纪公司基础数据更新，请重新登录!";
    case CF_ERROR_DATA_UPDATE_SERVERGROUP:    return "服务器组基础数据更新，请重新登录!";
    case CF_ERROR_DATA_UPDATE_SERVERADDR:     return "服务器组地址基础数据更新，请重新登录!";
    case CF_ERROR_DATA_UPDATE_ACCOUNT:        return "委托交易账户基础数据更新，请重新登录!";
    case CF_ERROR_DATA_UPDATE_STRATEGY:  	  return "交易策略基础数据更新，请重新登录!";
    case CF_ERROR_DATA_UPDATE_USER:           return "系统用户基础数据更新，请重新登录!";
    case CF_ERROR_DATA_UPDATE_ROLE:           return "角色基础数据更新，请重新登录!";

    case CF_ERROR_DATA_UPDATE_ROLEANDPRIVILEGE:   return "角色和权限关系更新，请重新登录!";
    case CF_ERROR_DATA_UPDATE_USERANDROLE:        return "用户和角色关系更新，请重新登录!";
    case CF_ERROR_DATA_UPDATE_USERANDORG:         return "用户和组织机构关系更新，请重新登录!";
    case CF_ERROR_DATA_UPDATE_USERANDPRODUCT:     return "用户和理财产品关系更新，请重新登录!";
    case CF_ERROR_DATA_UPDATE_STRATEGYANDORG:     return "交易策略和组织机构更新，请重新登录!";

    case CF_ERROR_DATA_QUOT_SUBSCRIBE:       return "订阅行情失败,请重新订阅!";
    case CF_ERROR_DATA_QUOT_UNSUBSCRIBE:     return "退订行情失败,请重新退订!";

	case CF_ERROR_DATA_STRATEGY_EXISTANDUSE: return "[%s]策略已经存在，而且处于启用状态,本次上传失败";
	case CF_ERROR_DATA_STRATEGY_SAVEDLLFAIL: return "存储策略dll失败";
	case CF_ERROR_DATA_STRATEGY_SAVEZIPFAIL: return "存储策略ZIP失败";
	case CF_ERROR_DATA_STRATEGY_NOTBELONGTOUPLOADER: return "策略或指标名已存在，为其他交易员使用，无权更新。";
	case CF_ERROR_DATA_STRATEGY_NOTEXIST: return "该策略不存在";
	case CF_ERROR_DATA_STRATEGY_NOTBELONGTOUPLOADER_PRIVATE: return "策略或指标属于其他交易员,私有不能下载";
	case CF_ERROR_DATA_READDLLFAIL: return "读取该策略dll文件失败";
	case CF_ERROR_DATA_READZIPFAIL: return "读取该策略源代码文件失败";
	case CF_ERROR_DATA_IndexIsUsing: return "[%s]指标所对应的[%s]策略处于运行当中,本次上传失败";
	case CF_ERROR_DATA_INDEX_NOTEXIST: return "该指标不存在";
	case CF_ERROR_DATA_INDEX_NOTBELONGTOUPLOADER_PRIVATE: return "该指标不是属于该交易员，而且该策略为私有";
	case CF_ERROR_DATA_INDEX_SAVEDLLFAIL: return "存储指标dll失败";
	case CF_ERROR_DATA_STRATEGY_NOTBELONGTOUPLOADER_USE: return "该策略不是属于该交易员，而且该策略为运行状态";
	case CF_ERROR_DATA_INSTANCE_NOTBELONGTOUPLOADER: return "该策略方案不是属于该交易员";
	case CF_ERROR_DATA_INSTANCE_NOTEXIST: return "该策略方案不存在";
	case CF_ERROR_DATA_STRATEGY_NOUSERNAME: return "没有上传人，不允许上传";
	case CF_ERROR_DATA_STRATEGY_NOTBELONGTOUPLOADER_PUBLIC: return "策略或指标源程序属于其他交易员不能下载";
	case CF_ERROR_DATA_UPLOAD_BACKFAIL: return "上传之前备份原有指标或者策略失败";
	case CF_ERROR_DATA_UPLOAD_RollBACKFAIL: return "备份的原有指标或者策略还原失败";
	case CF_ERROR_DATA_UPLOAD_FAIL:			return "本次上传失败，系统已经恢复原来的策略或者指标";
	case CF_ERROR_GET_COMMISSION_FAIL:			return "查询费率[%s]失败";
	case CF_ERROR_GET_MARGINATE_FAIL:			return "查询保证金率[%s]失败";
	case CF_ERROR_NO_ACCOUNT_FAIL:				return "查询失败,改子账号对应的主账号不存在";
	default:	return "未知错误";
	}
}