//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AlgoAutoOrder.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_MESSAGEBOXDIALOG            103
#define IDR_MAINFRAME                   128
#define IDR_AlgoAutoOrderTYPE           129
#define IDD_ALGOAUTOORDER_DIALOG        130
#define IDD_GENERALOPTIMIZE_DIALOG      131
#define IDD_OPTIMIZESETUP_DIALOG        132
#define IDD_DIALOG                      135
#define IDD_FEEDBACK_DIALOG             135
#define IDB_BITMAP_DEFAULT              140
#define IDB_BITMAP_PAUSE                141
#define IDB_BITMAP_DEL                  143
#define IDB_BITMAP_ADD                  145
#define IDB_BITMAP_STOP                 146
#define IDB_BITMAP_PLAY                 147
#define IDC_TAB                         1000
#define IDC_EDIT1                       1001
#define IDC_EDIT_PRICEFROM              1001
#define IDC_COMBO1                      1002
#define IDC_COMBO_RECALL                1002
#define IDC_COMBO_TIME                  1002
#define IDC_COMBO_                      1002
#define IDC_COMBO_MULTIPRICE            1002
#define IDC_COMBO2                      1003
#define IDC_COMBO_PRICECHANGE           1003
#define IDC_COMBO_PRICE                 1003
#define IDC_EDIT25                      1004
#define IDC_SPIN_PRICELIMIT             1004
#define IDC_EDIT_PRICETO                1004
#define IDC_BUTTON_NAMEADD              1005
#define IDC_BUTTON3                     1006
#define ID_BTN_OK                       1006
#define IDC_BUTTON_NAMEDELETE           1006
#define IDC_BUTTON_NAMEDEL              1006
#define IDC_BUTTON4                     1007
#define IDC_EDIT_INSTRUMENTCOUNT        1007
#define IDC_BUTTON_DETILADD             1007
#define IDC_BUTTON5                     1008
#define IDC_EDIT_PRICELIMIT             1008
#define IDC_BUTTON_DETILDELETE          1008
#define IDC_BUTTON_DETILDEL             1008
#define IDC_EDIT4                       1009
#define ID_BTN_CANCEL                   1009
#define IDC_EDIT_MULTIPLE               1009
#define IDC_EDIT26                      1010
#define IDC_BUTTON_DETILDELETE2         1010
#define IDC_BUTTON_SAVE                 1010
#define IDC_EDIT_MARKET                 1010
#define IDC_BTN_PAUSE                   1011
#define IDC_BUTTON_SAVESETUP            1011
#define IDC_BTN_PARAMSETUP              1012
#define IDC_SPIN2                       1013
#define IDC_SPIN_MARKET                 1013
#define IDC_EDIT_INSTRUMENTSTARTTIME    1014
#define IDC_SPIN_INSTRUMENTENDTIME      1015
#define IDC_EDIT_INSTRUMENTENDTIME      1016
#define IDC_SPIN_MARKETDEGREED          1017
#define IDC_EDIT_IDLETIME               1018
#define IDC_COMBO_IDLETIME              1019
#define IDC_EDIT_EXECUTETIME            1020
#define IDC_COMBO_EXECUTETIME           1021
#define IDC_EDIT_BASICPRICE             1022
#define IDC_COMBO_BASICPRICE            1023
#define IDC_EDIT_ORDERCOUNT             1026
#define IDC_COMBO_ORDERCOUNT            1027
#define IDC_EDIT_RESETORDERCOUNT        1028
#define IDC_COMBO_RESETORDERCOUNT1      1029
#define IDC_CHECK_ACTIVEOPTIMIZE        1030
#define IDC_COMBO_ACTIVEOPTIMIZE        1031
#define IDC_CHECK_OVERRETRYCOUNT        1032
#define IDC_COMBO10                     1033
#define IDC_COMBO_SLIDEPRICE            1033
#define IDC_EDIT_OVERRETRYCOUNT         1034
#define IDC_EDIT15                      1035
#define IDC_EDIT_SLIDEPRICE1            1035
#define IDC_LIST2                       1036
#define IDC_EDIT_SLIDPRICESPREAD2       1036
#define IDC_LIST_OPTIMIZENAME           1036
#define IDC_LIST_NAME                   1036
#define IDC_LIST3                       1037
#define IDC_EDIT_SLIDPRICESPREAD3       1037
#define IDC_LIST_OPTIMIZEDETIL          1037
#define IDC_LIST_DETIL                  1037
#define IDC_SLIDER1                     1038
#define IDC_EDIT_SLIDPRICESPREAD4       1038
#define IDC_SLIDER_MARKETDEGREED        1038
#define IDC_SLIDER_MARKET               1038
#define IDC_EDIT19                      1039
#define IDC_EDIT_SLIDEPRICE2            1039
#define IDC_EDIT27                      1040
#define IDC_COMBO_RESETORDERCOUNT2      1040
#define IDC_EDIT_SLIDEPRICE3            1040
#define IDC_EDIT20                      1041
#define IDC_EDIT_SLIDEPRICE4            1041
#define IDC_EDIT21                      1042
#define IDC_EDIT_SLIDEPRICE5            1042
#define IDC_EDIT22                      1043
#define IDC_COMBO12                     1043
#define IDC_EDIT_RESETORDERCOUNT3       1043
#define IDC_COMBO_RECOUNT               1043
#define IDC_EDIT23                      1044
#define IDC_EDIT_ORDERCOUNT1            1044
#define IDC_EDIT24                      1045
#define IDC_EDIT_ORDERCOUNT2            1045
#define IDC_EDIT28                      1046
#define IDC_SLID_MARKETDEGREED          1046
#define IDC_EDIT_ORDERCOUNT3            1046
#define IDC_EDIT29                      1047
#define IDC_CHECK_OVERRETRYTOTAL        1047
#define IDC_EDIT_ORDERCOUNT4            1047
#define IDC_EDIT_RECOUNT4               1047
#define IDC_EDIT30                      1048
#define IDC_COMBO_OVERRETRYTOTAL        1048
#define IDC_EDIT_ORDERCOUNT5            1048
#define IDC_EDIT_RECOUNT5               1048
#define IDC_EDIT_OVERRETRYTOTAL         1049
#define IDC_EDIT16                      1049
#define IDC_EDIT_INSTRUMENTID           1050
#define IDC_EDIT31                      1050
#define IDC_COMBO_BUYSELL               1051
#define IDC_EDIT32                      1051
#define IDC_COMBO_OPENCLOSE             1052
#define IDC_EDIT33                      1052
#define IDC_SPIN_INSTRUMENTSTARTTIME    1053
#define IDC_EDIT34                      1053
#define IDC_EDIT_RECOUNT1               1053
#define IDC_EDIT_MARKETDEGREED          1054
#define IDC_EDIT35                      1054
#define IDC_EDIT_RECOUNT2               1054
#define IDC_STATIC_SELLPRICE            1055
#define IDC_EDIT36                      1055
#define IDC_EDIT_RECOUNT3               1055
#define IDC_STATIC_LATESTPRICE          1056
#define IDC_STATIC_BUYPRICE             1057
#define IDC_STATIC_MIDDLEPRICE          1058
#define IDC_STATIC_YESTERDAYPRICE       1059
#define IDC_COMBO_SLIDPRICESPREAD       1060
#define IDC_EDIT_SLIDPRICESPREAD1       1061
#define IDC_EDIT_SLIDPRICESPREAD5       1062
#define IDC_EDIT_RESETORDERCOUNT1       1063
#define IDC_EDIT_RESETORDERCOUNT2       1064
#define IDC_EDIT_RESETORDERCOUNT4       1065
#define IDC_EDIT_RESETORDERCOUNT5       1066
#define IDC_CUSTOM_TIMEBAR              1069
#define IDC_CUSTOM_COUNTBAR             1070
#define IDC_STATIC_INSTRUMENTID         1071
#define IDC_STATIC_CONTRACT             1071
#define IDC_STATIC_INSTRUMENTCOUNT      1072
#define IDC_STATIC_LIMITPRICE           1073
#define IDC_STATIC_TRADEDERECTION       1074
#define IDC_STATIC_VOLUMEALL            1075
#define IDC_STATIC_VOLUMEAVERAGE        1076
#define IDC_STATIC_PRICE1               1077
#define IDC_STATIC_PRICE2               1078
#define IDC_STATIC_PRICE3               1079
#define IDC_STATIC_PRICE4               1080
#define IDC_STATIC_PRICE5               1081
#define IDC_STATIC_ORDERCOUNT1          1082
#define IDC_STATIC_ORDERCOUNT2          1083
#define IDC_STATIC_ORDERCOUNT3          1084
#define IDC_STATIC_ORDERCOUNT4          1085
#define IDC_STATIC_ORDERCOUNT5          1086
#define IDC_CUSTOM_TIME                 1087
#define IDC_CUSTOM_COUNT                1088
#define IDC_STATIC_DIRECTION            1089
#define IDC_STATIC_COUNT                1090
#define IDC_STATIC_COUNTTOTAL           1091
#define IDC_STATIC_PRICELIMIT           1092
#define IDC_STATIC_AVERAGEPRIVE         1093
#define IDC_STATIC_VOLUME1              1094
#define IDC_STATIC_VOLUME2              1095
#define IDC_STATIC_VOLUME3              1096
#define IDC_STATIC_VOLUME4              1097
#define IDC_STATIC_VOLUME5              1098
#define IDC_STATIC_AVERAGEPRIVE2        1099
#define IDC_CUSTOMTIME                  1101
#define IDC_CUSTOM2                     1102
#define IDC_CUSTOMCOUNT                 1102
#define IDC_DATETIMEPICKER_START        1103
#define IDC_DATETIMEPICKER2             1104
#define IDC_DATETIMEPICKER_END          1104
#define IDC_STATIC_FRME                 1105
#define IDC_STATIC_RULE                 1107
#define IDC_BUTTON_PLAY                 1109
#define IDC_BUTTON_STOP                 1110
#define IDC_STATIC_TITLE_1              1111
#define IDC_STATIC_TITLE1               1111
#define IDC_STATIC_TITLE_SELLPRICE      1111
#define IDC_STATIC_TITLE2               1112
#define IDC_STATIC_TITLE_LATESTPRICE    1112
#define IDC_STATIC_TITLE3               1113
#define IDC_STATIC_TITLE_BUYPRICE       1113
#define IDC_STATIC_TITLE4               1114
#define IDC_STATIC_TITLE_MIDDLEPRICE    1114
#define IDC_STATIC_TITLE5               1115
#define IDC_STATIC_TITLE_YESTERDAYPRICE 1115
#define IDC_STATIC_MUST1                1116
#define IDC_STATIC_MUST2                1117
#define IDC_STATIC_MUST3                1118
#define IDC_STATIC_MUST4                1119
#define IDC_PROGRESS1                   1121
#define IDC_CUSTOM1                     1122
#define IDC_STATIC_SPLIT                1126
#define IDC_EDIT2                       1127
#define IDC_EDIT_DOUBLECLICK            1127
#define IDC_EDIT_LISTNAME               1127
#define IDC_BUTTON2                     1129
#define IDC_STATIC_ORDERCOUNT           1130
#define IDC_STATIC_BUYSELL              1131
#define IDC_STATIC_START                1132
#define IDC_STATIC_END                  1133
#define IDC_STATIC_MARKETDEGREED        1134
#define IDC_STATIC_RESETORDERCOUNT      1135
#define IDC_STATIC_BASICPRICE           1136
#define IDC_STATIC_SLIDPRICESPREAD      1137
#define IDC_STATIC_RESETORDERCOUNT2     1138
#define IDC_STATIC_CLASS1               1139
#define IDC_STATIC_CLASS2               1140
#define IDC_STATIC_CLASS3               1141
#define IDC_STATIC_CLASS4               1142
#define IDC_STATIC_CLASS5               1143
#define IDC_STATIC_IDLETIME             1144
#define IDC_STATIC_EXECUTETIME          1145
#define IDC_STATIC_MARKET               1147
#define IDC_STATIC_SHOW                 1148
#define IDC_STATIC_MARKET2              1148
#define IDC_CHECK_MULTIPRICE            1149

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1150
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
