//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OptionStrategy.rc
//
#define IDD_OPTIONSTRATEGY_DIALOG       102
#define IDD_ORDERCONFIRMDLG             103
#define IDD_ORDERITEMDLG                104
#define IDR_MAINFRAME                   128
#define IDD_T_PIRCE_DIALOG              142
#define IDD_QUICKORDER_DIALOG           143
#define IDB_BITMAP_IMG                  144
#define IDB_BITMAPdelete                144
#define IDD_ANALYSE_DIALOG              150
#define IDD_PROBACHART_DIALOG           152
#define IDD_TRADEANALYSE_DIALOG         153
#define IDD_PROFIT_DIALOG               154
#define IDD_DIALOG_BITMAP               156
#define IDB_BITMAP_LINE                 158
#define IDI_ICON_UP                     163
#define IDB_BITMAPOptionStrategyBK_Deep 166
#define IDB_BITMAPOptionStrategyBK      167
#define IDB_BITMAPOptionStrategyTitle_Deep 168
#define IDB_BITMAPOptionStrategyTitle   169
#define IDB_BITMAPTPriceBK              171
#define IDB_BITMAPTPriceBK_Deep         174
#define IDB_BITMAPLineChartBottomBK     175
#define IDB_BITMAPBtnOrderBK            176
#define IDB_BITMAPTabListBoxIcon        177
#define IDB_BITMAPTabListBoxIcon_Deep   178
#define IDB_BITMAPTabProfitBK_Deep      179
#define IDB_BITMAPTabProfitBK           180
#define IDB_BITMAP_BTNCLOSE             182
#define IDI_ICON_DOWN                   198
#define IDB_BITMAP1                     200
#define IDB_BITMAP_BTNMIN               201
#define IDB_BITMAP_BTNMAX               202
#define IDB_BITMAP2                     203
#define IDB_BITMAP_BTNRESTORE           203
#define IDB_BITMAP_DELETEIMG            205
#define IDB_BITMAP3                     207
#define IDB_BITMAP_XLISTIMG             207
#define IDC_BUTTON_TITLE                1000
#define IDC_BUTTON_PRICE                1001
#define IDC_BUTTON_ORDER                1002
#define IDC_BUTTON_PROFIT               1003
#define IDC_SPLITTERH                   1004
#define IDC_SPLITTERV                   1005
#define IDC_STATIC_TITLE                1006
#define IDC_COMBO1                      1007
#define IDC_COMBO_EXCHANGE              1007
#define IDC_COMBO_STYLE                 1008
#define IDC_COMBO_INSTRUMENT            1009
#define IDC_STATIC_NAME                 1012
#define IDC_STATIC_LASTPRICE            1013
#define IDC_STATIC_LIMIT                1014
#define IDC_STATIC_LIMITPERCENT         1015
#define IDC_STATIC_BIDPRICE             1016
#define IDC_STATIC_ASKPRICE             1017
#define IDC_STATIC_HIGHTPRICE           1018
#define IDC_STATIC_LOWESTPRICE          1019
#define IDC_STATIC_VOLUME               1020
#define IDC_STATIC_LIMITDATE            1021
#define IDC_STATIC_UPDATETIME           1022
#define IDC_STATIC_NAME2                1023
#define IDC_STATIC_LASTPRICE2           1024
#define IDC_STATIC_LIMIT2               1025
#define IDC_STATIC_LIMITPERCENT2        1026
#define IDC_STATIC_BIDPRICE2            1027
#define IDC_STATIC_ASKPRICE2            1028
#define IDC_STATIC_HIGHTPRICE2          1029
#define IDC_STATIC_LOWESTPRICE2         1030
#define IDC_STATIC_VOLUME2              1031
#define IDC_STATIC_LIMITDATE2           1032
#define IDC_STATIC_UPDATETIME2          1033
#define IDC_LIST_BOX                    1033
#define IDC_BUTTON_LINE                 1034
#define IDC_LIST_ORDER                  1035
#define IDC_CUSTOM_TAB                  1036
#define IDC_STATIC_PROBACHART           1039
#define IDC_STATIC_                     1039
#define IDC_CHECK_UPDATETIME            1052
#define IDC_COMBO_UPDATETIME            1053
#define IDC_COMBO_STYLE1                1054
#define IDC_COMBO_STYLE2                1055
#define IDC_EDIT_PERCENT                1056
#define IDC_SPIN_PERCENT                1057
#define IDC_STATIC_PERCENT              1058
#define IDC_STATIC_DEADTIME             1059
#define IDC_DATETIMEPICKER_DEADTIME     1060
#define IDC_STATIC_REST                 1061
#define IDC_EDIT_REST                   1062
#define IDC_SPIN_REST                   1063
#define IDC_STATIC_PROFITCHART          1064
#define IDC_STATIC_UP                   1065
#define IDC_CUSTOM_THUMBNAIL            1066
#define IDC_STATIC_DOWN                 1066
#define IDC_BUTTON_CLOSE                1069
#define IDC_EDIT_PRICE                  1070
#define IDC_SPIN_PRICE                  1072
#define IDC_EDIT_COUNT                  1073
#define IDC_SPIN_COUNT                  1074
#define IDC_STATIC_DIRECT               1075
#define IDC_STATIC_INSTID               1076
#define IDC_STATIC_OFFSETFLAG           1077
#define IDC_LIST_QUOT                   1078
#define IDC_STATIC_NOTE                 1079
#define IDC_BUTTON_MAX                  1080
#define IDC_BUTTON_MIN                  1081

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        208
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
