//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MAManageClient.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_MAManageClientTYPE          129
#define IDD_DIALOG_BROKER_MANAGE        131
#define IDD_DIALOG_SERVER_MANAGE        132
#define IDD_DIALOG_PERMISSION_MANAGE    133
#define IDD_DIALOG_LOGON                134
#define IDD_DIALOG_MODIFY_PWD           135
#define IDD_DIALOG_BROKER_OPERATOR      136
#define IDD_DIALOG_SERVER_GROUP         137
#define IDD_DIALOG_SERVER_ADDR          138
#define IDD_MACLIENT_FORM               139
#define IDB_BITMAP_STATUS               140
#define IDI_ICON_DEL                    145
#define IDI_ICON_MODIFY                 146
#define IDI_ICON_REFRESH                147
#define IDI_ICON_ADD                    149
#define IDD_DIALOG_ACCOUNT              150
#define IDD_DIALOG_ACCOUNT_OPERATOR     151
#define IDD_DOCK_BAR                    152
#define IDD_TREECTRL                    153
#define IDD_DIALOG_TOOL_BAR             154
#define IDI_ICON_STOP                   155
#define IDD_DIALOG_USER_SET             156
#define IDD_DIALOG_INFO                 157
#define IDI_ICON_NOENTRY                158
#define IDR_MENU_TREE                   159
#define IDR_MENU_LIST                   160
#define IDI_ICON_ARROW_UP               162
#define IDI_ICON_ARROW_DOWN             163
#define IDD_DIALOG_BATCH_ADD_ACCOUNT    164
#define IDI_ICON_MESSAGE                165
#define IDD_DIALOG_MSG_SEND             166
#define IDD_DIALOG_MSG_DETAIL           167
#define IDC_LIST_QUOTE_ADDR             1002
#define IDC_EDIT_ACCOUNT                1003
#define IDC_EDIT_OLD_PWD                1004
#define IDC_BUTTON_BROKER_MDF           1005
#define IDC_EDIT_BROKER_CODE            1006
#define IDC_EDIT_GROUP_NAME             1007
#define IDC_EDIT_PWD                    1008
#define IDC_EDIT_NEW_PWD                1009
#define IDC_BUTTON_BROKER_REFRESH       1010
#define IDC_EDIT_COMPANY                1011
#define IDC_EDIT_PORT                   1012
#define IDC_CHECK_REMEMBER              1013
#define IDC_EDIT_PWD_CONFIRM            1014
#define IDC_BUTTON_BROKER_DEL           1015
#define IDC_EDIT_ADDR                   1016
#define IDC_BUTTON_BROKER_ADD           1017
#define IDC_LIST_BROKER                 1018
#define IDC_BUTTON_TRADE_ADDR_ADD       1019
#define IDC_BUTTON_TRADE_ADDR_DEL       1020
#define IDC_BUTTON_GROUP_DEL            1021
#define IDC_BUTTON_GROUP_ADD            1022
#define IDC_COMBO_BROKER                1023
#define IDC_LIST_GROUP                  1024
#define IDC_BUTTON_TRADE_ADDR_TEST      1025
#define IDC_BUTTON_TRADE_ADDR_MODIFY    1025
#define IDC_BUTTON_QUOTE_ADDR_ADD       1026
#define IDC_BUTTON_QUOTE_ADDR_DEL       1027
#define IDC_BUTTON_QUOTE_ADDR_TEST      1028
#define IDC_BUTTON_QUOTE_ADDR_MODIFY    1028
#define IDC_LIST_TRADE_ADDR             1029
#define IDC_BUTTON_GROUP_MODIFY         1030
#define IDC_CHECK_GROUP_SHARE           1031
#define IDC_COMBO_PERMISSION_TYPE       1034
#define IDC_BUTTON_ADD_NAME             1035
#define IDC_BUTTON_DEL_NAME             1036
#define IDC_TREE_PERMISSION             1037
#define IDC_LIST_PERMISSION_NAME        1038
#define IDC_BUTTON_COMMIT               1039
#define IDC_CHECK1                      1040
#define IDC_TAB_VIEW                    1041
#define IDC_LIST_BKG_ACCOUNT            1044
#define IDC_COMBO1                      1045
#define IDC_COMBO_PAGE_LIST             1045
#define IDC_COMBO_TOOL_BAR_OWNER        1045
#define IDC_COMBO_BATCH_PERMISSION      1045
#define IDC_COMBO_BATCH_ACCOUNT_STATUS  1046
#define IDC_EDIT_USER_NAME              1047
#define IDC_EDIT_ACCOUNT_PWD            1048
#define IDC_EDITACCOUNT_PWD_CONFIRM     1049
#define IDC_EDIT_CONTACTINFO            1050
#define IDC_EDIT_IDCARD_NO              1051
#define IDC_COMBO_ACCOUNT_STATUS        1052
#define IDC_COMBO_IDCARD_TYPE           1053
#define IDC_COMBO_PERMISSION            1054
#define IDC_STATIC_TOTAL                1055
#define IDC_STATIC_CUR_PAGE             1056
#define IDC_STATIC_JUMP_TO              1057
#define IDC_STATIC_HOME                 1058
#define IDC_STATIC_END                  1059
#define IDC_STATIC_PRE                  1060
#define IDC_STATIC_NEXT                 1061
#define IDC_EDIT_ROW                    1062
#define IDC_STATIC_EVERY_PAGE           1063
#define IDC_STATIC_ROW                  1064
#define IDC_EDIT_TOOL_BAR_ACCOUNT       1068
#define IDC_BUTTON_SEARCH               1069
#define IDC_RADIO1                      1070
#define IDC_RADIO2                      1071
#define IDC_CHECK_ATTR1                 1072
#define IDC_BUTTON_PERMISSION_SET       1073
#define IDC_STATIC_INFO                 1074
#define IDC_DATE_VALID                  1075
#define IDC_RADIO_VALID_FOREVER         1076
#define IDC_RADIO_USER_VALID_DATE       1077
#define IDC_DATETIMEPICKER1             1078
#define IDC_CHECK_DATE                  1079
#define IDC_EDIT_PATH                   1080
#define IDC_BUTTON_BROWSE               1081
#define IDC_DATE_BATCH                  1082
#define IDC_PROGRESS1                   1084
#define IDC_EDIT_TITLE                  1086
#define IDC_EDIT_CONTENT                1087
#define IDC_BTN_SEND_MSG                1088
#define IDC_LIST_MSG                    1089
#define IDC_TREE_USER                   1090
#define IDC_BTN_SHOW_USER_LIST          1091
#define IDC_BTN_SELECT_ALL              1092
#define IDC_BTN_UNSELECT_ALL            1093
#define IDC_BTN_ONLINE_USER             1094
#define IDC_LIST_USER                   1095
#define IDC_DATETIMEPICKER_MSG          1096
#define IDC_STATIC_TITLE                1097
#define IDC_STATIC_CONTENT              1098
#define IDC_STATIC_EXPIRED              1099
#define IDC_STATIC_GROUP                1100
#define IDC_RADIO_COMMON                1101
#define IDC_RADIO_PERSONAL              1102
#define IDC_BTN_MSG_SEND_STATUS         1103
#define IDC_EDIT1                       1103
#define IDC_EDIT_MSG_DETAIL_TITLE       1103
#define IDC_EDIT2                       1104
#define IDC_EDIT_MSG_DETAIL_CONTENT     1104
#define IDC_EDIT3                       1105
#define IDC_EDIT_MSG_SEND_LIST          1105
#define IDC_EDIT4                       1106
#define IDC_EDIT_MSG_WAIT_LIST          1106
#define IDC_BUTTON1                     1107
#define IDC_STATIC_SEND_TOTAL           1108
#define IDC_STATIC_WAIT_TOTAL           1109
#define ID_32786                        32786
#define ID_32787                        32787
#define ID_32788                        32788
#define ID_32789                        32789
#define ID_32790                        32790
#define ID_MODIFY_PWD                   32791
#define ID_QUIT                         32792
#define ID_BROKER_MANAGE                32793
#define ID_SERVER_MANAGE                32794
#define ID_PERMISSION_SET               32795
#define ID_32796                        32796
#define ID_MANAGE_LIST                  32797
#define ID_TOOL_ADD                     32802
#define ID_TOOL_MODIFY                  32803
#define ID_TOOL_DEL                     32804
#define ID_TOOL_REFRESH                 32805
#define ID_32806                        32806
#define ID_32807                        32807
#define ID_32808                        32808
#define ID_32809                        32809
#define ID_TOOL_STOP                    32810
#define ID_32811                        32811
#define ID_32812                        32812
#define ID_SYSTEM_SET                   32813
#define ID_USER_SET                     32814
#define ID_32815                        32815
#define ID_IDR_32816                    32816
#define ID_IDR_32817                    32817
#define ID_POP_MODIFY                   32818
#define ID_POP_DEL                      32819
#define ID_POP_STOP                     32820
#define ID_32821                        32821
#define ID_TOOL_BATCH_ADD               32822
#define ID_IDR_32823                    32823
#define ID_IDR_EXPORT_LIST              32824
#define ID_TOOL_MESSAGE                 32825
#define ID_32826                        32826

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1110
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
